spring:
 datasource:
    url: jdbc:mysql://localhost:3306/hibernatedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    
 network:
  businessType: wholesale
  locationType: local
